//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.shelly.solormonitor.ui.gesture;

import android.content.Context;

public final class BaseActivityHelper_
    extends BaseActivityHelper
{

    private Context context_;

    private BaseActivityHelper_(Context context) {
        context_ = context;
        init_();
    }

    public static BaseActivityHelper_ getInstance_(Context context) {
        return new BaseActivityHelper_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
