//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.ty.solormonitor.ui.gesture;

import android.content.Context;

public final class SlideActivityHelper_
    extends SlideActivityHelper
{

    private Context context_;

    private SlideActivityHelper_(Context context) {
        context_ = context;
        init_();
    }

    public static SlideActivityHelper_ getInstance_(Context context) {
        return new SlideActivityHelper_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
